---
title: "RDA_our_method"
author: "Zitong Zhang"
# date: 
output: html_document
params: 
  subj_name: "func_20150417"
  data_folder: "../../Results/Rdata/RDA/CDF_freqtrun4_totaltime280/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Import functions --------------------------------------------------------

# rm(list=ls())
file_path = "../Functions"
file.sources = list.files(path = file_path, pattern = "*.R$", full.names = TRUE)
sapply(file.sources, source)

library(tidyverse)
library(gridExtra)
library(R.matlab)
library(data.table)
```

## Read in network information for the L/R side 
```{r}
# Get network information for the L/R side 
path = paste0("../../Processed_FunctionalData/",params$subj_name,"/")
path_vec = c(path)

edge_time_mat_list = vector(mode = "list", length = 2)
locs_mat_list = vector(mode = "list", length = 2)
mnx_vec_list = vector(mode = "list", length = 2)
dFF_mat_list = vector(mode = "list", length = 2)
iso_inds_list = vector(mode = "list", length = 2)
non_iso_inds_list = vector(mode = "list", length = 2)


for(m in 1:length(path_vec)){ 
  path = path_vec[m]
  
  ### Read information from data
  edge_time_mat = as.matrix(read.csv(paste(path, '/EdgeTime.csv', sep='')))
  edge_time_mat = edge_time_mat[,-1]
  
  avai.inds = as.matrix(read.csv(paste(path,'/AvaiNeurons.csv',sep='')))
  avai.inds = avai.inds[,-1];
  
  locs.all = as.matrix(read.csv(paste(path,'/locs_all.csv',sep='')))
  locs.all = locs.all[,-1]
  locs_mat = locs.all[avai.inds,]
  
  mnx.all = as.matrix(read.csv(paste(path,'/mnx.csv',sep='')))
  mnx.all = mnx.all[,-1]
  mnx_vec = mnx.all[avai.inds]
  
  dFF.all = as.matrix(fread(paste(path,'/dFF.csv',sep='')))
  dFF.all = dFF.all[,-1]
  dFF_mat = dFF.all[avai.inds,]
  
  ### Split each zebrafish into left and right
  inds_L = which(locs_mat[,2]<0)
  inds_R = which(locs_mat[,2]>0)
  
  edge_time_mat_L = edge_time_mat[inds_L, inds_L]
  edge_time_mat_R = edge_time_mat[inds_R, inds_R]
  
  locs_mat_L = locs_mat[inds_L,]
  locs_mat_R = locs_mat[inds_R,]
  
  mnx_vec_L = mnx_vec[inds_L]
  mnx_vec_R = mnx_vec[inds_R]
  
  dFF_mat_L = dFF_mat[inds_L,]
  dFF_mat_R = dFF_mat[inds_R,]
  
  
  iso_inds_L = which(rowSums(edge_time_mat_L<Inf)<=0)
  iso_inds_R = which(rowSums(edge_time_mat_R<Inf)<=0)
  
  non_iso_inds_L = setdiff(1:nrow(edge_time_mat_L), iso_inds_L)
  non_iso_inds_R = setdiff(1:nrow(edge_time_mat_R), iso_inds_R)
  
  edge_time_mat_L = edge_time_mat_L[non_iso_inds_L, non_iso_inds_L]
  edge_time_mat_R = edge_time_mat_R[non_iso_inds_R, non_iso_inds_R]
  
  edge_time_mat_list[c(2*m-1,2*m)] = list(edge_time_mat_L, edge_time_mat_R)
  locs_mat_list[c(2*m-1,2*m)] = list(locs_mat_L, locs_mat_R)
  mnx_vec_list[c(2*m-1,2*m)] = list(mnx_vec_L, mnx_vec_R)
  dFF_mat_list[c(2*m-1,2*m)] = list(dFF_mat_L, dFF_mat_R)
  
  iso_inds_list[c(2*m-1,2*m)] = list(iso_inds_L, iso_inds_R)
  non_iso_inds_list[c(2*m-1,2*m)] = list(non_iso_inds_L, non_iso_inds_R)
  
}

```

## Read in data analysis results
```{r}
### Read in data analysis results
data_folder = paste0(params$data_folder, params$subj_name, "/") 
path_vec = list.files(data_folder, full.names = TRUE, recursive = TRUE)

res_list = vector(mode = "list", length = length(path_vec))

for(m in 1:length(path_vec)){ 
  path = path_vec[m]
  ### Read in results from data
  load(path)
  res_list[[m]] = res
}


### Collect from all subjects: clusters_list, center_pdf_array, v_vec
clusters_list = lapply(res_list, function(res) res$clusters_list)
center_pdf_array_list = lapply(res_list, function(res) res$center_pdf_array)
v_vec_list = lapply(res_list, function(res) res$v_vec)
t_vec = res$t_vec
n0_mat_list = lapply(v_vec_list, function(v_vec) n0_vec2mat(n0_vec = v_vec/(t_vec[2]-t_vec[1])))

### Fix spike intensity 
for (ind in 1:length(center_pdf_array_list)) {
  if (dim(center_pdf_array_list[[ind]])[3]<length(t_vec)) {
    center_pdf_array_list[[ind]] = get_center_pdf_array_v2(edge_time_mat_list = edge_time_mat_list[ind], clusters_list = clusters_list[ind], n0_mat_list = n0_mat_list[ind], t_vec = t_vec)
}
}

```


## Visualize estimated intensities
```{r}
if (!exists("t_vec")) {
  t_vec = seq(0,336,1)
}
### Get connecting probabilities
order_clus_1 = order(rowSums(apply(center_pdf_array_list[[1]], 
      MARGIN = c(1,2),
      function(vec)sum(vec*(t_vec[2]-t_vec[1])))), 
      decreasing = TRUE)
order_clus_2 = order(rowSums(apply(center_pdf_array_list[[2]], 
      MARGIN = c(1,2),
      function(vec)sum(vec*(t_vec[2]-t_vec[1])))), 
      decreasing = TRUE)

### Visualize estimated connecting intensities 
clus_size_list = lapply(clusters_list, function(clusters)sapply(clusters,length))

pdf_array_1 = center_pdf_array_list[[1]][order_clus_1,order_clus_1, ,drop=FALSE][1:3,1:3,]
pdf_array_2 = center_pdf_array_list[[2]][order_clus_2,order_clus_2, ,drop=FALSE][1:3,1:3,]
### Manually shift intensities
global_shift = 20
pdf_array_2[,,1:(length(t_vec)-global_shift)] = pdf_array_2[,,(global_shift+1):length(t_vec)]
pdf_array_2[,,(length(t_vec)-global_shift+1):length(t_vec)] = 0

pdf_array_list = list(pdf_array_1, pdf_array_2)
clus_size_vec_1 = clus_size_list[[1]][order_clus_1][1:3]
clus_size_vec_2 = clus_size_list[[2]][order_clus_2][1:3]
tmp = plot_pdf_array_v3(pdf_array_list = pdf_array_list, 
                       clus_size_vec_1 = clus_size_vec_1,
                       clus_size_vec_2 = clus_size_vec_2,
                       t_vec = t_vec, 
                       y_lim = c(0,max(unlist(pdf_array_list))))
g3 = tmp$g
grid.arrange(g3)
big.df = tmp$big.df
inter_quan_len_df = big.df %>%
  mutate(inter_quan_len = quantile_95-quantile_5) %>%
  select(ind_subj, clus.pair, inter_quan_len) %>%
  group_by(clus.pair, ind_subj) %>%
  summarise(inter_quan_len=unique(inter_quan_len)) %>%
  ungroup()
print(inter_quan_len_df)
```

```{r}

g1 = plot_pdf_array_v2(pdf_array_list = center_pdf_array_list[[1]][order_clus_1,order_clus_1, ,drop=FALSE], 
                        pdf_true_array = center_pdf_array_list[[1]][order_clus_1,order_clus_1, ,drop=FALSE],
                        clus_size_vec = clus_size_list[[1]][order_clus_1],
                        t_vec = t_vec, x_lim = c(), y_lim = c(0,max(unlist(center_pdf_array_list[[1]]))))

g2 = plot_pdf_array_v2(pdf_array_list = center_pdf_array_list[[2]][order_clus_2,order_clus_2, ,drop=FALSE], 
                        pdf_true_array = center_pdf_array_list[[2]][order_clus_2,order_clus_2, ,drop=FALSE],
                        clus_size_vec = clus_size_list[[2]][order_clus_2],
                        t_vec = t_vec, x_lim = c(), y_lim = c(0,max(unlist(center_pdf_array_list[[2]]))))

grid.arrange(g1, g2, ncol=2)


```



## Visualize estimated time shifts
```{r}
### Get memberships for ALL nodes
membership_list = lapply(clusters_list, clus2mem)
membership_list[[1]] = clus2mem(clusters_list[[1]][order_clus_1])
membership_list[[2]] = clus2mem(clusters_list[[2]][order_clus_2])


for (m in 1:length(membership_list)) {
  N_node = nrow(locs_mat_list[[m]])
  mem_tmp = rep(0,N_node)
  mem_tmp[non_iso_inds_list[[m]]] = membership_list[[m]]
  membership_list[[m]] = mem_tmp
}
```

```{r}
### Plot time shifts distribution
data = tibble(v_vec=unlist(v_vec_list), 
              membership=c(membership_list[[1]][non_iso_inds_list[[1]]], membership_list[[2]][non_iso_inds_list[[2]]]), 
              subj=rep(1:length(v_vec_list), times=sapply(v_vec_list,length)))

v_range = data %>%
  filter(membership<=3) %>%
  group_by(membership) %>%
  summarise(y0 = min(v_vec),
         y25 = quantile(v_vec, 0.25),
         y50 = median(v_vec),
         y75 = quantile(v_vec, 0.75),
         y100 = max(v_vec)) %>%
  ungroup()


g4 <- v_range %>%
  ggplot()+
  geom_boxplot(aes(ymin = y0, lower = y25, middle = y50, 
                   upper = y75, ymax = y100,
                   x=as.factor(membership),
                   group=as.factor(membership),
                   color=as.factor(membership)),
               stat = "identity") +
  scale_color_manual(values=palette()[1+1:3]) +
  theme_bw()+
  theme(legend.position = "none") +
  # facet_wrap(~subj) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank(), axis.title.y = element_blank()) +
  xlab('Membership')

print(g4)

```

```{r}
v_range = data %>%
  filter(membership<=3) %>%
  group_by(membership) %>%
  summarise(y0 = min(v_vec),
         y25 = quantile(v_vec, 0.25),
         y50 = median(v_vec),
         y75 = quantile(v_vec, 0.75),
         y100 = max(v_vec)) %>%
  ungroup()
g5 <- data %>%
  filter(membership<=3) %>%
  ggplot(aes(x=v_vec,group=as.factor(membership),
             color=as.factor(membership)))+
  geom_histogram( aes(y = ..density.., fill=as.factor(membership)), bins = 15, position = 'identity', alpha=0.4, size=0) +
  geom_density( aes(), alpha=0.6) +
  geom_segment(aes(x=v_range$min,xend=v_range$max, 
                         y=0, yend=0,
                         # alpha = 0.1,
                         color=as_factor(v_range$membership)), 
               inherit.aes = FALSE,
               arrow=arrow(angle = 90,
                           length = unit(0.08, "inches"), 
                           ends='both'),
               size = 1,
               alpha=0.9) +
  # geom_point(aes(x=v_range$median, y=0,
  #                color=as_factor(v_range$membership)), size=2) +
  scale_color_manual(values=palette()[1+1:4]) +
  scale_fill_manual(values=palette()[1+1:4]) +
  theme_bw()+
  theme(legend.position = "none") +
  # facet_wrap(~subj) +
  scale_x_continuous() +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank(), axis.title.y = element_blank()) +
  xlab('Time shifts (min)')

print(g5)
```


```{r}
### Get Wan's result
dat=readMat(paste('../../Raw_data/to_shizhe/','Leader_',substr(params$subj_name, start=nchar(params$subj_name)-7, stop=nchar(params$subj_name)),'.mat',sep=''))
activeTime_vec = dat$activeTime * 60
patternTime_vec = dat$patternTime * 60

### Let time shift for non-active nodes be NA
for (m in 1:length(v_vec_list)) {
  N_node = nrow(locs_mat_list[[m]])
  v_vec_tmp = rep(NA,N_node)
  v_vec_tmp[non_iso_inds_list[[m]]] = v_vec_list[[m]]
  v_vec_list[[m]] = v_vec_tmp
}

ggplot(data = data.frame(activeTime_vec=activeTime_vec,
                         v_vec=unlist(v_vec_list),
                         mem=as_factor(unlist(membership_list))
                         )) + 
  geom_point(aes(x=activeTime_vec, y=v_vec, color=mem)) +
  scale_color_manual(values=palette()[c(8,2:6)]) +
  xlab('Activation time by Wan (pp. e7)') +
  ylab('Our estimation')

ggplot(data = data.frame(activeTime_vec=activeTime_vec,
                         patternTime_vec=patternTime_vec,
                         v_vec=unlist(v_vec_list),
                         mem=as_factor(unlist(membership_list))
                         )) + 
  geom_point(aes(x=patternTime_vec, y=v_vec, color=mem)) +
  scale_color_manual(values=palette()[c(8,2:6)]) +
  xlab('Patterning time by Wan (pp. e7)') +
  ylab('Our estimation')

```
```{r}
ind1 = which(unlist(v_vec_list)>20 & activeTime_vec<=1 &
              unlist(membership_list)==1)[1]
ind2 = which(abs(unlist(v_vec_list)-unlist(v_vec_list)[ind1])<10 &
               abs(activeTime_vec-unlist(v_vec_list)[ind1])<10 &
              unlist(membership_list)==1)[1]
unlist(v_vec_list)[ind1]
activeTime_vec[ind1]
unlist(v_vec_list)[ind2]
activeTime_vec[ind2]

plot_local_traces(locs = locs_mat[c(ind2, ind1),], reduced.dFF = dFF_mat[c(ind2, ind1),], snapshot_mins = c(0,43,48,49), window_length=1)

### Cluster 2
ind3 = which(unlist(v_vec_list)<200 & unlist(v_vec_list)>150 & activeTime_vec<=1 &
              unlist(membership_list)==2)[1]
ind4 = which(abs(unlist(v_vec_list)-unlist(v_vec_list)[ind3])<50 &
               abs(activeTime_vec-unlist(v_vec_list))<50 &
              unlist(membership_list)==2)[1]
unlist(v_vec_list)[ind3]
activeTime_vec[ind3]
unlist(v_vec_list)[ind4]
activeTime_vec[ind4]

plot_local_traces(locs = locs_mat[c(ind4, ind3),], reduced.dFF = dFF_mat[c(ind4, ind3),], snapshot_mins = c(0,157,171,193),window_length=1)

```



## Visualize estimated clusters with spatial location

```{r}

### Spatial location  ----

data = as.data.frame(reduce(locs_mat_list,rbind))
colnames(data) = c('AP','LR','DV')
data = cbind(data, 
             membership=as.factor(unlist(membership_list)),
             subj=rep(1:length(membership_list),
                      times=sapply(membership_list,length)))

# lims = data.frame(coord=c("AP","DV","LR"), xmin=c(-0.5, 0, -2),xmax=c(9,140,3))
# g<- data %>% 
#   pivot_longer(cols = c('AP','LR','DV'), names_to = "coord", values_to = "loc") %>%
#   ggplot(aes(x=loc,
#                      group=membership,
#                      color=membership))+
#   geom_density( aes(), alpha=0.6, position = 'dodge') +
#   scale_color_manual(values=palette()[c(8,2:6)]) +
#   theme_bw()+
#   theme(legend.position = "none") +
#   facet_wrap(~coord, scales='free',ncol=1) +
#   xlab('') +
#   # scale_x_continuous(limits = c(-2, 6))+
#   theme(axis.ticks.y = element_blank(), axis.text.y = element_blank(), axis.title.y = element_blank()) +
#   scale_y_continuous(position = "right")
# print(g)

```
```{r}
library(plotly)
fig = plot_ly(data, x = ~LR, y = ~AP, z = ~DV, color = ~membership, 
              # colors = c(palette()[c(8,2:6)]),
              colors = c(`0`=palette()[8], 
                         `1`=palette()[2],
                         `2`=palette()[3],
                         `3`=palette()[4],
                         `4`=palette()[5],
                         `5`=palette()[6]),
              type = "scatter3d")
fig
```


## Visualize estimated clusters with mnx+/- indicator

```{r}
### mnx decomposition  ----

data = tibble(subj=rep(1:length(membership_list),sapply(membership_list,length)),
              membership=unlist(membership_list),
              mnx=as.factor(unlist(mnx_vec_list)), 
              islet=NA) 

data_2 = data %>% 
  mutate(mnx=factor(mnx,levels=c(1,0)), islet=as.factor(as.numeric(islet)), 
         membership=factor(membership, levels=c(0,max(membership):1))) 

data_2_left = data_2 %>% filter(subj==1) %>% mutate(membership=fct_drop(membership))
data_2_right = data_2 %>% filter(subj==2) %>% mutate(membership=fct_drop(membership))

fill_color = c(`0`=palette()[8],
               `1`=palette()[2],
               `2`=palette()[3],
               `3`=palette()[4],
               `4`=palette()[5],
               `5`=palette()[6])
### Left spine
g1 = data_2_left %>%
  mutate(membership=factor(membership,levels=c(0,1,2,3,4))) %>%
  ggplot(mapping = aes(fill=mnx,x=membership)) +
  scale_fill_manual(values=fill_color) +
  geom_bar(position="fill") +
  geom_text(data = data_2_left %>% 
              count(membership, mnx) %>% group_by(membership) %>% 
              summarise(perc=round(n/sum(n),3), mnx=mnx) %>% 
              arrange(desc(mnx), .by_group = TRUE) ,
            aes(x = membership, label = scales::percent(perc), y=perc, fill=NULL), 
            position = position_fill(0.5), size=2.5)+
  # scale_x_discrete(labels=c("mnx+","mnx-"))+
  xlab("")+
  theme_bw()+
  theme(legend.position = 'none', 
        panel.grid  = element_blank(),
        # axis.text = element_blank(),
        axis.text.y = element_blank(), 
        axis.title = element_blank(),  
        axis.title.y = element_blank(), 
        axis.ticks.y = element_blank())

### Right spine
g2 = data_2_right %>%
  mutate(membership=factor(membership,levels=c(1,2,3,4))) %>%
  ggplot(mapping = aes(fill=mnx,x=membership)) +
  scale_fill_manual(values=fill_color) +
  geom_bar(position="fill") +
  geom_text(data = data_2_right %>% 
              count(membership, mnx) %>% group_by(membership) %>% 
              summarise(perc=round(n/sum(n),3), mnx=mnx) %>% 
              arrange(desc(mnx), .by_group = TRUE) ,
            aes(x = membership, label = scales::percent(perc), y=perc, fill=NULL), 
            position = position_fill(0.5), size=2.5)+
  # scale_x_discrete(labels=c("mnx+","mnx-"))+
  xlab("")+
  theme_bw()+
  theme(legend.position = 'none', 
        panel.grid  = element_blank(),
        # axis.text = element_blank(),
        axis.text.y = element_blank(), 
        axis.title = element_blank(),  
        axis.title.y = element_blank(), 
        axis.ticks.y = element_blank())

grid.arrange(g1, g2, ncol=2)
```

