---
title: "RDA_our_method"
author: "Zitong Zhang"
# date: 
output: html_document
params: 
  subj_name: "func_20150417"
  data_folder: "../../Results/Rdata/RDA/CDF_v9_rmvtop_Nrestart20_freqtrun3_totaltime290/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Import functions --------------------------------------------------------

# rm(list=ls())
file_path = "../Functions"
file.sources = list.files(path = file_path, pattern = "*.R$", full.names = TRUE)
sapply(file.sources, source)

library(tidyverse)
library(gridExtra)
library(R.matlab)
library(data.table)
```


## Read in data analysis results
```{r}
### Read in data analysis results
data_folder = paste0(params$data_folder, params$subj_name, "/") 
path_vec = list.files(data_folder, full.names = TRUE, recursive = TRUE)

res_list = vector(mode = "list", length = length(path_vec))
ICL_history_list = compl_log_lik_history_list = time_total_list = list()

for(m in 1:length(path_vec)){ 
  path = path_vec[m]
  ### Read in results from data
  load(path)
  res_list[[m]] = res
  ICL_history_list[[m]] = ICL_history
  compl_log_lik_history_list[[m]] = compl_log_lik_history
  time_total_list[[m]] = time_total
}


### Collect from all subjects: clusters_list, center_pdf_array, v_vec
clusters_list = lapply(res_list, function(res) res$clusters_list)
center_pdf_array_list = lapply(res_list, function(res) res$center_pdf_array)
v_vec_list = lapply(res_list, function(res) res$v_vec)
t_vec = res$t_vec
n0_mat_list = lapply(v_vec_list, function(v_vec) n0_vec2mat(n0_vec = v_vec/(t_vec[2]-t_vec[1])))

```


## Visualize estimated intensities
```{r}
clus_size_list = lapply(clusters_list, function(clusters)sapply(clusters,length))

g_list = list()
for (i in 1:length(center_pdf_array_list)) {
  order_clus = order(rowSums(apply(center_pdf_array_list[[i]], 
      MARGIN = c(1,2),
      function(vec)sum(vec*(t_vec[2]-t_vec[1])))), 
      decreasing = TRUE)
  pdf_array = center_pdf_array_list[[i]][order_clus,order_clus, ,drop=FALSE]
  
  g1 = plot_pdf_array_v2(pdf_array_list = pdf_array, 
                        pdf_true_array = pdf_array,
                        clus_size_vec = clus_size_list[[i]][order_clus],
                        t_vec = t_vec, x_lim = c(), y_lim = c(0,max(pdf_array)))
 
  g_list[[i]] = g1
}

do.call(grid.arrange, c(g_list,ncol=length(g_list)))

```



## Max likelihood vs Iteration
```{r}
for (compl_log_lik_history in compl_log_lik_history_list) {
 max_loglik = sapply(1:length(compl_log_lik_history),
                     function(x)max(compl_log_lik_history[1:x]))
 plot(max_loglik,type='b') 
 abline(v=which.max(max_loglik),col=2)
 print(max(max_loglik))
}
```

